// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using web_server.Database;

#nullable disable

namespace web_server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("web_server.Models.DBModels.BalanceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CashFlowId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserDTOUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CashFlowId");

                    b.HasIndex("UserDTOUserId");

                    b.ToTable("BalanceHistory");
                });

            modelBuilder.Entity("web_server.Models.DBModels.CashFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CashFlow");
                });

            modelBuilder.Entity("web_server.Models.DBModels.ConnectionToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChatDTOId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatDTOId");

                    b.ToTable("ConnectionTokens");
                });

            modelBuilder.Entity("web_server.Models.DBModels.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChatDTOId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatDTOId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("web_server.Models.DBModels.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChatDTOId")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime>("MessageTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatDTOId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("web_server.Models.DBModels.NotificationTokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TokenKey")
                        .HasColumnType("text");

                    b.Property<string>("TokenValue")
                        .HasColumnType("text");

                    b.Property<int?>("UserDTOUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserDTOUserId");

                    b.ToTable("NotificationTokens");
                });

            modelBuilder.Entity("web_server.Models.DBModels.PaidLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PaidCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ScheduleDTOId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleDTOId");

                    b.ToTable("PaidLesson");
                });

            modelBuilder.Entity("web_server.Models.DBModels.RescheduledLessons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Initiator")
                        .HasColumnType("text");

                    b.Property<DateTime>("NewTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OldTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int?>("ScheduleDTOId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleDTOId");

                    b.ToTable("RescheduledLessons");
                });

            modelBuilder.Entity("web_server.Models.DBModels.SiteContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteContacts");
                });

            modelBuilder.Entity("web_server.Models.DBModels.SkippedDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InitPaid")
                        .HasColumnType("integer");

                    b.Property<int?>("ScheduleDTOId")
                        .HasColumnType("integer");

                    b.Property<bool>("WasWarn")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleDTOId");

                    b.ToTable("SkippedDates");
                });

            modelBuilder.Entity("web_server.Models.DBModels.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("web_server.Models.DBModels.UserCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<bool>("Repaid")
                        .HasColumnType("boolean");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduleSkippedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StudentDTOUserId")
                        .HasColumnType("integer");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentDTOUserId");

                    b.ToTable("UserCredit");
                });

            modelBuilder.Entity("web_server.Models.DBModels.UserDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("RegistrationDTOId")
                        .HasColumnType("integer");

                    b.Property<int?>("TutorDTOUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationDTOId");

                    b.HasIndex("TutorDTOUserId");

                    b.ToTable("UserDates");
                });

            modelBuilder.Entity("web_server.Models.DBModels.UserMoney", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentDTOUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentDTOUserId");

                    b.ToTable("UserMoney");
                });

            modelBuilder.Entity("web_server.Models.DTO.ChatDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InChat")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("web_server.Models.DTO.CourseDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GoalId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("web_server.Models.DTO.GoalDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("web_server.Models.DTO.NotificationTaskDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NotifKey")
                        .HasColumnType("text");

                    b.Property<bool>("NotifValue")
                        .HasColumnType("boolean");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("NotificationTasks");
                });

            modelBuilder.Entity("web_server.Models.DTO.NotificationsDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<bool>("Readed")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("web_server.Models.DTO.ReadyDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ScheduleDTOId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleDTOId");

                    b.ToTable("ReadyDate");
                });

            modelBuilder.Entity("web_server.Models.DTO.RegistrationDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("ExistUserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("NewUserGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("web_server.Models.DTO.ScheduleDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Looped")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("NewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RemoveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RescheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TutorFullName")
                        .HasColumnType("text");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("WaitPaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TutorId");

                    b.HasIndex("UserId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("web_server.Models.DTO.TutorCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int?>("TutorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorCourses");
                });

            modelBuilder.Entity("web_server.Models.DTO.UserDTO", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("ActiveToken")
                        .HasColumnType("text");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("web_server.Models.DTO.ManagerDTO", b =>
                {
                    b.HasBaseType("web_server.Models.DTO.UserDTO");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("web_server.Models.DTO.StudentDTO", b =>
                {
                    b.HasBaseType("web_server.Models.DTO.UserDTO");

                    b.Property<bool>("FirstLogin")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedInThisMonth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartWaitPayment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UsedTrial")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasFirstPayment")
                        .HasColumnType("boolean");

                    b.Property<string>("Wish")
                        .HasColumnType("text");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("web_server.Models.DTO.TutorDTO", b =>
                {
                    b.HasBaseType("web_server.Models.DTO.UserDTO");

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.ToTable("Tutors", (string)null);
                });

            modelBuilder.Entity("web_server.Models.DBModels.BalanceHistory", b =>
                {
                    b.HasOne("web_server.Models.DBModels.CashFlow", "CashFlow")
                        .WithMany()
                        .HasForeignKey("CashFlowId");

                    b.HasOne("web_server.Models.DTO.UserDTO", null)
                        .WithMany("BalanceHistory")
                        .HasForeignKey("UserDTOUserId");

                    b.Navigation("CashFlow");
                });

            modelBuilder.Entity("web_server.Models.DBModels.ConnectionToken", b =>
                {
                    b.HasOne("web_server.Models.DTO.ChatDTO", null)
                        .WithMany("ConnectionTokens")
                        .HasForeignKey("ChatDTOId");
                });

            modelBuilder.Entity("web_server.Models.DBModels.Contact", b =>
                {
                    b.HasOne("web_server.Models.DTO.ChatDTO", null)
                        .WithMany("Contacts")
                        .HasForeignKey("ChatDTOId");
                });

            modelBuilder.Entity("web_server.Models.DBModels.Messages", b =>
                {
                    b.HasOne("web_server.Models.DTO.ChatDTO", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatDTOId");
                });

            modelBuilder.Entity("web_server.Models.DBModels.NotificationTokens", b =>
                {
                    b.HasOne("web_server.Models.DTO.UserDTO", null)
                        .WithMany("NotificationTokens")
                        .HasForeignKey("UserDTOUserId");
                });

            modelBuilder.Entity("web_server.Models.DBModels.PaidLesson", b =>
                {
                    b.HasOne("web_server.Models.DTO.ScheduleDTO", null)
                        .WithMany("PaidLessons")
                        .HasForeignKey("ScheduleDTOId");
                });

            modelBuilder.Entity("web_server.Models.DBModels.RescheduledLessons", b =>
                {
                    b.HasOne("web_server.Models.DTO.ScheduleDTO", null)
                        .WithMany("RescheduledLessons")
                        .HasForeignKey("ScheduleDTOId");
                });

            modelBuilder.Entity("web_server.Models.DBModels.SkippedDate", b =>
                {
                    b.HasOne("web_server.Models.DTO.ScheduleDTO", null)
                        .WithMany("SkippedDates")
                        .HasForeignKey("ScheduleDTOId");
                });

            modelBuilder.Entity("web_server.Models.DBModels.UserCredit", b =>
                {
                    b.HasOne("web_server.Models.DTO.StudentDTO", null)
                        .WithMany("Credit")
                        .HasForeignKey("StudentDTOUserId");
                });

            modelBuilder.Entity("web_server.Models.DBModels.UserDate", b =>
                {
                    b.HasOne("web_server.Models.DTO.RegistrationDTO", null)
                        .WithMany("WantThis")
                        .HasForeignKey("RegistrationDTOId");

                    b.HasOne("web_server.Models.DTO.TutorDTO", null)
                        .WithMany("UserDates")
                        .HasForeignKey("TutorDTOUserId");
                });

            modelBuilder.Entity("web_server.Models.DBModels.UserMoney", b =>
                {
                    b.HasOne("web_server.Models.DTO.StudentDTO", null)
                        .WithMany("Money")
                        .HasForeignKey("StudentDTOUserId");
                });

            modelBuilder.Entity("web_server.Models.DTO.ChatDTO", b =>
                {
                    b.HasOne("web_server.Models.DTO.UserDTO", "User")
                        .WithOne("Chat")
                        .HasForeignKey("web_server.Models.DTO.ChatDTO", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("web_server.Models.DTO.CourseDTO", b =>
                {
                    b.HasOne("web_server.Models.DTO.GoalDTO", "Goal")
                        .WithMany("Courses")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("web_server.Models.DTO.NotificationTaskDTO", b =>
                {
                    b.HasOne("web_server.Models.DTO.ScheduleDTO", "Schedule")
                        .WithMany("Tasks")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("web_server.Models.DTO.NotificationsDTO", b =>
                {
                    b.HasOne("web_server.Models.DTO.UserDTO", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("web_server.Models.DTO.ReadyDate", b =>
                {
                    b.HasOne("web_server.Models.DTO.ScheduleDTO", null)
                        .WithMany("ReadyDates")
                        .HasForeignKey("ScheduleDTOId");
                });

            modelBuilder.Entity("web_server.Models.DTO.RegistrationDTO", b =>
                {
                    b.HasOne("web_server.Models.DTO.CourseDTO", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("web_server.Models.DTO.ScheduleDTO", b =>
                {
                    b.HasOne("web_server.Models.DTO.CourseDTO", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_server.Models.DTO.TutorDTO", "Tutor")
                        .WithMany("Schedules")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_server.Models.DTO.StudentDTO", "Student")
                        .WithMany("Schedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("web_server.Models.DTO.TutorCourse", b =>
                {
                    b.HasOne("web_server.Models.DTO.CourseDTO", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("web_server.Models.DTO.TutorDTO", "Tutor")
                        .WithMany("Courses")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("web_server.Models.DTO.ManagerDTO", b =>
                {
                    b.HasOne("web_server.Models.DTO.UserDTO", null)
                        .WithOne()
                        .HasForeignKey("web_server.Models.DTO.ManagerDTO", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("web_server.Models.DTO.StudentDTO", b =>
                {
                    b.HasOne("web_server.Models.DTO.UserDTO", null)
                        .WithOne()
                        .HasForeignKey("web_server.Models.DTO.StudentDTO", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("web_server.Models.DTO.TutorDTO", b =>
                {
                    b.HasOne("web_server.Models.DTO.UserDTO", null)
                        .WithOne()
                        .HasForeignKey("web_server.Models.DTO.TutorDTO", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("web_server.Models.DTO.ChatDTO", b =>
                {
                    b.Navigation("ConnectionTokens");

                    b.Navigation("Contacts");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("web_server.Models.DTO.GoalDTO", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("web_server.Models.DTO.RegistrationDTO", b =>
                {
                    b.Navigation("WantThis");
                });

            modelBuilder.Entity("web_server.Models.DTO.ScheduleDTO", b =>
                {
                    b.Navigation("PaidLessons");

                    b.Navigation("ReadyDates");

                    b.Navigation("RescheduledLessons");

                    b.Navigation("SkippedDates");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("web_server.Models.DTO.UserDTO", b =>
                {
                    b.Navigation("BalanceHistory");

                    b.Navigation("Chat");

                    b.Navigation("NotificationTokens");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("web_server.Models.DTO.StudentDTO", b =>
                {
                    b.Navigation("Credit");

                    b.Navigation("Money");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("web_server.Models.DTO.TutorDTO", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Schedules");

                    b.Navigation("UserDates");
                });
#pragma warning restore 612, 618
        }
    }
}
